# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.2
  - 5.3
  - 5.4

# omitting "script:" will default to phpunit
script: phpunit --bootstrap=tests/bootstrap.php tests
